### ISSUE TITLE
[Feature] 이슈 상세 페이지, 디자인 페이지

### ISSUE THREAD

**Issue by naarang** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#13]
## 🔨 Description

- 이슈 상세 페이지 레이아웃
- 디자인 페이지 레이아웃 

## ✅ Tasks

- [x] 이슈 상세 페이지 레이아웃
- [x] 상단의 step 위젯 개발
- [x] 문제 정의 페이지 레이아웃
- [ ] HMW 페이지 레이아웃
- [x] Crazy 페이지 레이아웃
- [x] 스케치 페이지 레이아웃
