### ISSUE TITLE
[Feature] navigation bar 생성

### ISSUE THREAD

**Issue by bianbbc87** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#2]
## 🔨 Description
네비게이션 바 생성
- .

## ✅ Tasks

- [x] navigation bar news, home, board, my 선택 생성
- [x] 버튼 클릭 시 페이지 이동 로직 구현
- [x] svg 이미지 추가, 이미지 선택 시 색상 변경 추가
- [x] svg 이미지 선택 시 색상 변경 추가

## Problem
- [ ] label(text) 색상 변경이 안 되는 문제 발생
- [ ] 배경색을 white, transparent로 지정해도 얕은 보라색이 보이는 문제 발생

## ▪ Etc
- [ ] route 할 페이지 스크린 생성 해야함.

<img width="492" alt="image" src="https://github.com/GDSC-DGU/2024-SolutionChallenge-InGlo-client/assets/129590633/ea75dcb2-a2e4-4b9a-b9ee-6cbe52dc5b05">
