### ISSUE TITLE
[Feature] map(home) 페이지 구현

### ISSUE THREAD

**Issue by bianbbc87** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#24]
## 🔨 Description

- map 페이지 구현

## ✅ Tasks

- [ ] 국가 검색 기능
- [ ] 국가 검색 후 국가 선택 기능
- [ ] 경계 다각형

**Comment by bianbbc87** [comment]
## 🔨 Description

- map 페이지 상세 구현

## ✅ Tasks

- [ ] map 페이지 css 변경
- [ ] 검색 키워드 '한글' 추가
- [ ] flutter와 react 이벤트 연결

## ▪ Etc
