### ISSUE TITLE
[Feature] 게시글 작성 기능 디테일

### ISSUE THREAD

**Issue by bianbbc87** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#27]
## 🔨 Description

- 게시글 작성 기능 디테일

## ✅ Tasks

- [ ] title, content 입력
- [ ] html editor 추가
- [ ] font style, image, link, table, hr 추가
