### ISSUE TITLE
[Feature] 게시글 상세 디테일

### ISSUE THREAD

**Issue by bianbbc87** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#29]
## 🔨 Description

- 게시글 상세 디테일

## ✅ Tasks

- [ ] html encoding 출력
- [ ] 피드백 입력 기능 추가

**Comment by bianbbc87** [comment]
## 🔨 Description

- 게시글 상세 디테일

## ✅ Tasks

- [ ] 버튼 색상 스타일 변경

## ▪ Etc
