### ISSUE TITLE
[Feature] login, account 페이지 레이아웃 생성

### ISSUE THREAD

**Issue by bianbbc87** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#6]
## 🔨 Description

- login, account 페이지 레이아웃 생성함

## ✅ Tasks

- [ ] 배경 이미지 추가
- [ ] textformfield 추가
- [ ] border, label 스타일 추가

## ▪ Etc
- [ ] font 적용 필요
- [ ] onChange 이벤트 추가 필요
- [ ] 유효성 검사 필요
- [ ] country, language options로 변경 필요
