### ISSUE TITLE
[Feature] login, account 페이지 디테일 완성

### ISSUE THREAD

**Issue by bianbbc87** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#8]
## 🔨 Description

- login, account 페이지 이벤트, 폰트 등 디테일 수정이 필요함.
- #6 이슈에 이어서 생성함.

## ✅ Tasks

- [ ] font 적용
- [ ] onChange 이벤트 추가
- [ ] 유효성 검사 필요
- [ ] country, language options로 변경 필요
- [ ] db 연결
