### ISSUE TITLE
[Feature] 안드로이드, IOS 파이어베이스 세팅 

### ISSUE THREAD

**Issue by dongkyeomjang** [GDSC-DGU/2024-SolutionChallenge-InGlo-client#9]
## 🔨 Description
안드로이드와 IOS 각각에 대하여 파이어베이스를 사용하기 위한 세팅을 진행한다.
- .

## ✅ Tasks

- [x] Firebase 프로젝트 생성
- [x] Firebase 프로젝트 세팅(안드로이드)
- [x] Firebase 프로젝트 세팅(IOS)
- [x] Flutter에 의존성 추가
- [x] Firebase 초기화 코드 작성
- [x] 테스팅
